name: Order Cleanup Cron

on:
  schedule:
    # 10분마다 실행 (실제 환경에서는 필요에 따라 조정)
    - cron: "*/10 * * * *"
  workflow_dispatch: # 수동 실행 옵션

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger order cleanup API
        run: |
          curl -X POST ${{ secrets.APP_URL }}/api/orders/cleanup \
          -H "Authorization: Bearer ${{ secrets.CRON_API_KEY }}" \
          -H "Content-Type: application/json"
